name: Update GitHub Stats SVGs

on:
  schedule:
    - cron: '0 0 * * *' # Раз в день в полночь
  workflow_dispatch: # Возможность запустить вручную
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  update-svgs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create assets folder
        run: mkdir -p assets

      - name: Download Streak Stats
        run: |
          curl -s "https://streak-stats.demolab.com?user=gimeshli-a&locale=en&mode=daily&theme=dracula&hide_border=false&border_radius=5&order=3" -o assets/streak-stats.svg

      - name: Download Activity Graph
        run: |
          curl -s "https://github-readme-activity-graph.vercel.app/graph?username=gimeshli-a&radius=8&theme=noctis-minimus&area=true&order=5" -o assets/activity-graph.svg

      - name: Download Profile Details (Alternative to Readme Stats)
        run: |
          curl -s "https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=gimeshli-a&theme=dracula" -o assets/github-stats.svg

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/*.svg
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update GitHub stats SVGs" && git push)
